/**
 * 2-dars — «Привет!» (Liden & Denz, «Я ❤ Русский Язык», 1-urok asosida).
 * Kitob dastur sifatida ishlatiladi: mavzu, so'zlar va grammatika undan,
 * gap/dialog/mashqlar esa o'zimizniki (kitob matnlari ko'chirilmaydi).
 * 1-darsda (alifbo) o'rganilgan so'zlar lug'atga qayta qo'shilmaydi.
 */
import type { SeedExercise, SeedQuestion } from "../seed-exercises";
import type { VocabSeed } from "./types";

export const R01_ROUNDS: { title: string; words: VocabSeed[] }[] = [
  {
    title: "1-bosqich",
    words: [
      { emoji: "👋", word: "Привет", transcription: "privyét", pos: "ibora", uz: "Salom (do'stlarga)", def: "Неофициальное приветствие: так здороваются с друзьями.", ex: "Привет! Сто лет не виделись!", exUz: "Salom! Yuz yil ko'rishmadik!" },
      { emoji: "🤝", word: "Здравствуйте", transcription: "zdrástvuyte", pos: "ibora", uz: "Assalomu alaykum (rasmiy)", def: "Вежливое приветствие: так здороваются со взрослыми и незнакомыми людьми.", ex: "Здравствуйте! Можно войти?", exUz: "Assalomu alaykum! Kirsam maylimi?" },
      { emoji: "🙋", word: "Пока", transcription: "paká", pos: "ibora", uz: "Xayr (do'stlarga)", def: "Неофициальное прощание: так прощаются с друзьями.", ex: "Пока! Увидимся завтра!", exUz: "Xayr! Ertaga ko'rishamiz!" },
      { emoji: "🚪", word: "До свидания", transcription: "da svidániya", pos: "ibora", uz: "Xayr, ko'rishguncha (rasmiy)", def: "Вежливое прощание.", ex: "До свидания! Спасибо за урок!", exUz: "Xayr! Dars uchun rahmat!" },
      { emoji: "🙏", word: "Спасибо", transcription: "spasíba", pos: "ibora", uz: "Rahmat", def: "Так говорят, когда благодарят человека.", ex: "Спасибо за вкусный обед!", exUz: "Mazali tushlik uchun rahmat!" },
      { emoji: "😊", word: "Пожалуйста", transcription: "pazhálusta", pos: "ibora", uz: "Arzimaydi; marhamat; iltimos", def: "Ответ на «спасибо», а также вежливая просьба.", ex: "Чай, пожалуйста!", exUz: "Choy, iltimos!" },
      { emoji: "🙇", word: "Извините", transcription: "izviníte", pos: "ibora", uz: "Kechirasiz", def: "Так вежливо обращаются к незнакомому человеку или просят прощения.", ex: "Извините, я опоздал!", exUz: "Kechirasiz, kechikdim!" },
      { emoji: "🌅", word: "Доброе утро", transcription: "dóbraye útra", pos: "ibora", uz: "Xayrli tong", def: "Приветствие утром.", ex: "Доброе утро! Кофе уже готов.", exUz: "Xayrli tong! Qahva allaqachon tayyor." },
      { emoji: "☀️", word: "Добрый день", transcription: "dóbriy dyen'", pos: "ibora", uz: "Xayrli kun", def: "Вежливое приветствие днём.", ex: "Добрый день! Чем могу помочь?", exUz: "Xayrli kun! Qanday yordam bera olaman?" },
      { emoji: "🌙", word: "Добрый вечер", transcription: "dóbriy vyéchir", pos: "ibora", uz: "Xayrli kech", def: "Вежливое приветствие вечером.", ex: "Добрый вечер! Ужин на столе.", exUz: "Xayrli kech! Kechki ovqat stolda." },
    ],
  },
  {
    title: "2-bosqich",
    words: [
      { emoji: "😃", word: "Очень приятно", transcription: "óchin' priyátna", pos: "ibora", uz: "Tanishganimdan xursandman", def: "Так говорят, когда знакомятся с человеком.", ex: "— Я Азиз. — Очень приятно, а я Лола!", exUz: "— Men Aziz. — Tanishganimdan xursandman, men esa Lola!" },
      { emoji: "🪪", word: "Меня зовут", transcription: "minyá zavút", pos: "ibora", uz: "Mening ismim …", def: "Так говорят, когда называют своё имя.", ex: "Меня зовут Бонд. Джеймс Бонд.", exUz: "Mening ismim Bond. Jeyms Bond." },
      { emoji: "💬", word: "Как дела", transcription: "kak dilá", pos: "ibora", uz: "Ishlaring qalay?", def: "Вопрос о том, как у человека жизнь и настроение.", ex: "Привет, как дела? Что нового?", exUz: "Salom, ishlar qalay? Nima yangiliklar?" },
      { emoji: "👍", word: "Хорошо", transcription: "kharashó", pos: "ravish", uz: "Yaxshi", def: "Так говорят, когда всё в порядке.", ex: "Всё хорошо, что хорошо кончается.", exUz: "Oxiri yaxshi bo'lsa, hammasi yaxshi (maqol)." },
      { emoji: "👎", word: "Плохо", transcription: "plókha", pos: "ravish", uz: "Yomon", def: "Противоположность слову «хорошо».", ex: "Без кофе мне утром плохо.", exUz: "Ertalab qahvasiz holim yomon." },
      { emoji: "😐", word: "Нормально", transcription: "narmál'na", pos: "ravish", uz: "Normal, yomon emas", def: "Не очень хорошо, но и не плохо.", ex: "— Как экзамен? — Нормально!", exUz: "— Imtihon qalay? — Normal!" },
      { emoji: "😕", word: "Так себе", transcription: "tak sibyé", pos: "ibora", uz: "Unchalik emas", def: "Не очень хорошо.", ex: "Фильм так себе, скучный.", exUz: "Film unchalik emas, zerikarli." },
      { emoji: "👩‍🏫", word: "Преподаватель", transcription: "prepadavátel'", pos: "ot", uz: "O'qituvchi", def: "Человек, который учит студентов.", ex: "Наш преподаватель очень весёлый.", exUz: "O'qituvchimiz juda quvnoq." },
      { emoji: "🗂️", word: "Секретарь", transcription: "sikritár'", pos: "ot", uz: "Kotib(a)", def: "Человек, который работает в офисе: отвечает на телефон, пишет письма.", ex: "Секретарь знает всё в офисе.", exUz: "Kotiba ofisdagi hamma narsani biladi." },
      { emoji: "👔", word: "Директор", transcription: "diréktar", pos: "ot", uz: "Direktor", def: "Главный человек на фирме или в школе.", ex: "Директор сегодня в хорошем настроении.", exUz: "Direktor bugun yaxshi kayfiyatda." },
    ],
  },
  {
    title: "3-bosqich",
    words: [
      { emoji: "💼", word: "Бизнесмен", transcription: "biznismén", pos: "ot", uz: "Biznesmen, tadbirkor", def: "Человек, у которого свой бизнес.", ex: "Бизнесмен всегда занят.", exUz: "Biznesmen doim band." },
      { emoji: "🐕", word: "Собака", transcription: "sabáka", pos: "ot", uz: "It", def: "Домашнее животное, друг человека.", ex: "Собака — друг человека.", exUz: "It — insonning do'sti." },
      { emoji: "📱", word: "Телефон", transcription: "tilifón", pos: "ot", uz: "Telefon", def: "По нему говорят с людьми, которые далеко.", ex: "Мой телефон всегда со мной.", exUz: "Telefonim doim men bilan." },
      { emoji: "📖", word: "Книга", transcription: "kníga", pos: "ot", uz: "Kitob", def: "Её читают.", ex: "Книга — лучший подарок.", exUz: "Kitob — eng yaxshi sovg'a." },
      { emoji: "👓", word: "Очки", transcription: "achkí", pos: "ot", uz: "Ko'zoynak", def: "Их носят, чтобы лучше видеть.", ex: "Где мои очки? Они на голове!", exUz: "Ko'zoynagim qayerda? Boshimda ekan!" },
      { emoji: "📰", word: "Журнал", transcription: "zhurnál", pos: "ot", uz: "Jurnal", def: "Издание с фотографиями и статьями.", ex: "Журнал о моде лежит на столе.", exUz: "Moda haqidagi jurnal stol ustida." },
      { emoji: "✏️", word: "Карандаш", transcription: "karandásh", pos: "ot", uz: "Qalam", def: "Им пишут и рисуют.", ex: "Карандаш сломался на экзамене!", exUz: "Qalam imtihonda sinib qoldi!" },
      { emoji: "📓", word: "Тетрадь", transcription: "titrát'", pos: "ot", uz: "Daftar", def: "В ней пишут на уроке.", ex: "Тетрадь по математике — синяя.", exUz: "Matematika daftari — ko'k." },
      { emoji: "📘", word: "Словарь", transcription: "slavár'", pos: "ot", uz: "Lug'at (kitob)", def: "Книга, где можно узнать, что значит слово.", ex: "Словарь помогает понять новые слова.", exUz: "Lug'at yangi so'zlarni tushunishga yordam beradi." },
      { emoji: "📻", word: "Радио", transcription: "rádio", pos: "ot", uz: "Radio", def: "По нему слушают музыку и новости.", ex: "Папа слушает радио в машине.", exUz: "Dadam mashinada radio tinglaydi." },
    ],
  },
  {
    title: "4-bosqich",
    words: [
      { emoji: "🛏️", word: "Кровать", transcription: "kravát'", pos: "ot", uz: "Karavot", def: "На ней спят.", ex: "Кровать такая мягкая — не хочу вставать!", exUz: "Karavot juda yumshoq — turgim kelmayapti!" },
      { emoji: "👜", word: "Сумка", transcription: "súmka", pos: "ot", uz: "Sumka", def: "В ней носят вещи.", ex: "Сумка у мамы — как волшебный мир.", exUz: "Onamning sumkasi — sehrli dunyo kabi." },
      { emoji: "☕", word: "Кофе", transcription: "kófe", pos: "ot", uz: "Qahva", def: "Горячий напиток. Слово мужского рода: кофе — он.", ex: "Утром кофе, вечером чай.", exUz: "Ertalab qahva, kechqurun choy." },
      { emoji: "🍰", word: "Кафе", transcription: "kafé", pos: "ot", uz: "Kafe", def: "Место, где пьют кофе и едят.", ex: "Это кафе — моё любимое место.", exUz: "Bu kafe — mening sevimli joyim." },
      { emoji: "🪵", word: "Стол", transcription: "stol", pos: "ot", uz: "Stol", def: "Мебель: за ним едят и работают.", ex: "Стол на кухне — центр семьи.", exUz: "Oshxonadagi stol — oilaning markazi." },
      { emoji: "🪑", word: "Стул", transcription: "stul", pos: "ot", uz: "Stul", def: "На нём сидят.", ex: "Осторожно, стул сломан!", exUz: "Ehtiyot bo'l, stul singan!" },
      { emoji: "🚇", word: "Метро", transcription: "mitró", pos: "ot", uz: "Metro", def: "Подземный городской транспорт.", ex: "Метро в Ташкенте очень красивое.", exUz: "Toshkent metrosi juda chiroyli." },
      { emoji: "🏛️", word: "Музей", transcription: "muzyéy", pos: "ot", uz: "Muzey", def: "Там можно смотреть картины и старые вещи.", ex: "Музей Эрмитаж — огромный.", exUz: "Ermitaj muzeyi — ulkan." },
      { emoji: "🧑‍🎓", word: "Студент", transcription: "studyént", pos: "ot", uz: "Talaba", def: "Человек, который учится в университете.", ex: "Студент спит на лекции.", exUz: "Talaba ma'ruzada uxlayapti." },
      { emoji: "🌊", word: "Море", transcription: "mórye", pos: "ot", uz: "Dengiz", def: "Большая солёная вода.", ex: "Море зовёт!", exUz: "Dengiz chorlayapti!" },
    ],
  },
];

const listen = (word: string, options: string[], explanation?: string): SeedQuestion => ({
  prompt: "Eshitgan so'zingizni toping",
  audio: word,
  options,
  correct: options.indexOf(word),
  explanation,
});
const pick = (prompt: string, options: string[], correct: number, explanation?: string): SeedQuestion => ({
  prompt,
  options,
  correct,
  explanation,
});

const KTO = ["Кто это?", "Что это?"];
const ZOVUT = ["меня", "тебя", "его", "её", "нас", "вас", "их"];
const MOOD = ["очень хорошо", "хорошо", "нормально", "так себе", "плохо"];

export const R01_EXERCISES: SeedExercise[] = [
  {
    title: "Tinglang va toping",
    skill: "Tinglash",
    kind: "listen",
    instructions: "So'z ovoz chiqarib o'qiladi. Eshitgan so'zingizni toping. Qayta eshitish uchun tugmani bosing.",
    questions: [
      listen("привет", ["привет", "пока", "приятно", "пожалуйста"]),
      listen("здравствуйте", ["до свидания", "здравствуйте", "спасибо", "извините"]),
      listen("пока", ["как", "пока", "так", "привет"]),
      listen("спасибо", ["собака", "пожалуйста", "спасибо", "хорошо"]),
      listen("пожалуйста", ["пожалуйста", "пока", "спасибо", "приятно"]),
      listen("извините", ["здравствуйте", "извините", "до свидания", "очень"]),
      listen("хорошо", ["плохо", "нормально", "хорошо", "молоко"], "хорошо [харашо] — urg'usiz «о» [a] bo'lib eshitiladi."),
      listen("плохо", ["плохо", "хорошо", "пока", "так себе"]),
      listen("приятно", ["привет", "приятно", "понятно", "пожалуйста"]),
      listen("до свидания", ["здравствуйте", "доброе утро", "до свидания", "спасибо"]),
    ],
  },
  {
    title: "Bu nima?",
    skill: "Rasm",
    kind: "picture",
    instructions: "Rasmga qarang va uning ruscha nomini toping.",
    questions: [
      pick("🐕", ["собака", "студент", "стол", "окно"], 0),
      pick("☕", ["кафе", "кофе", "книга", "море"], 1, "Кофе — ichimlik, кафе — joy."),
      pick("📖", ["журнал", "тетрадь", "книга", "лампа"], 2),
      pick("⌚", ["часы", "очки", "стул", "радио"], 0),
      pick("🪑", ["стол", "стул", "окно", "метро"], 1, "Стул — stul, стол — stol."),
      pick("👓", ["часы", "окно", "очки", "телефон"], 2),
      pick("📞", ["радио", "телефон", "журнал", "карандаш"], 1),
      pick("✏️", ["карандаш", "тетрадь", "книга", "лампа"], 0),
      pick("🌊", ["метро", "мама", "кафе", "море"], 3),
      pick("💡", ["мама", "лампа", "стол", "радио"], 1),
    ],
  },
  {
    title: "Кто это? или Что это?",
    skill: "Grammatika",
    kind: "choice",
    instructions:
      "Odam yoki hayvon haqida — «Кто это?», narsa haqida — «Что это?» deb so'raladi. So'zga mos savolni tanlang.",
    questions: [
      pick("студент", KTO, 0),
      pick("стол", KTO, 1),
      pick("собака", KTO, 0, "Hayvonlar haqida ham — «Кто это?»"),
      pick("мама", KTO, 0),
      pick("кофе", KTO, 1),
      pick("преподаватель", KTO, 0),
      pick("окно", KTO, 1),
      pick("спортсмен", KTO, 0),
      pick("часы", KTO, 1),
      pick("Анна", KTO, 0),
    ],
  },
  {
    title: "Nima deysiz?",
    skill: "Vaziyat",
    kind: "situation",
    instructions: "Vaziyatni o'qing va unga mos ruscha iborani tanlang.",
    questions: [
      pick("Ertalab do'stingizni ko'rdingiz.", ["Привет!", "Здравствуйте, Анна Петровна!", "До свидания!", "Спасибо!"], 0, "Do'st bilan — «Привет!» (norasmiy)."),
      pick("Darsga kirdingiz, o'qituvchi bilan salomlashing.", ["Привет!", "Здравствуйте!", "Пока!", "Пожалуйста!"], 1, "Kattalar va notanishlar bilan — «Здравствуйте!»"),
      pick("Do'stingiz bilan xayrlashyapsiz.", ["Здравствуйте!", "Спасибо!", "Пока!", "Извините!"], 2),
      pick("O'qituvchi bilan xayrlashyapsiz.", ["Пока!", "До свидания!", "Привет!", "Очень приятно!"], 1),
      pick("Sizga qahva berishdi.", ["Пожалуйста!", "Привет!", "Спасибо!", "Извините!"], 2),
      pick("Sizga «Спасибо!» deyishdi.", ["Спасибо!", "Пожалуйста!", "Пока!", "Хорошо!"], 1),
      pick("Ko'chada notanish odamdan metro qayerdaligini so'ramoqchisiz.", ["Привет, где метро?", "Пока, где метро?", "Извините, где метро?", "Спасибо, где метро?"], 2),
      pick("Yangi odam bilan tanishdingiz.", ["До свидания!", "Очень приятно!", "Пожалуйста!", "Плохо."], 1),
      pick("Kechqurun qo'shningizni ko'rdingiz.", ["Доброе утро!", "Добрый день!", "Добрый вечер!", "Пока!"], 2),
      pick("Tushlik paytida direktorni ko'rdingiz.", ["Добрый день!", "Доброе утро!", "Добрый вечер!", "Привет!"], 0),
    ],
  },
  {
    title: "Juftini toping",
    skill: "Juftlik",
    kind: "match",
    instructions: "Chapdagi ruscha so'zni, keyin o'ngdagi tarjimasini bosing. Hamma juftlarni ulang.",
    questions: [
      ["привет|salom", "пока|xayr", "спасибо|rahmat", "пожалуйста|arzimaydi"],
      ["хорошо|yaxshi", "плохо|yomon", "нормально|normal", "так себе|unchalik emas"],
      ["стол|stol", "стул|stul", "окно|deraza", "книга|kitob"],
      ["мама|ona", "папа|ota", "студент|talaba", "преподаватель|o'qituvchi"],
      ["тут|shu yerda", "там|u yerda", "слева|chap tomonda", "справа|o'ng tomonda"],
      ["один|bir", "два|ikki", "три|uch", "четыре|to'rt"],
      ["пять|besh", "шесть|olti", "семь|yetti", "восемь|sakkiz"],
      ["девять|to'qqiz", "десять|o'n", "одиннадцать|o'n bir", "двадцать|yigirma"],
      ["кто?|kim?", "что?|nima?", "где?|qayerda?", "как?|qanday?"],
      ["часы|soat", "очки|ko'zoynak", "собака|it", "кофе|qahva"],
    ].map((options) => ({ prompt: "Juftlarni ulang", options })),
  },
  {
    title: "Suhbatni davom ettiring",
    skill: "Dialog",
    kind: "dialog",
    instructions: "Suhbatdoshingiz gapirdi. Unga mos javobni tanlang.",
    questions: [
      pick("Привет! Как тебя зовут?", ["Меня зовут Маша.", "Её зовут Маша.", "Это стол.", "Спасибо."], 0),
      pick("Здравствуйте! Как Вас зовут?", ["Тебя зовут Олег.", "Меня зовут Олег Петрович.", "Пока!", "Хорошо."], 1),
      pick("Меня зовут Анна.", ["Пожалуйста!", "До свидания!", "Очень приятно!", "Плохо."], 2),
      pick("Как дела?", ["Спасибо, хорошо. А у тебя?", "Меня зовут Коля.", "Это книга.", "Он студент."], 0),
      pick("Кто это?", ["Это стол.", "Это Иван. Он студент.", "Да, спасибо.", "Хорошо."], 1),
      pick("Что это?", ["Это Анна.", "Он там.", "Это телефон.", "Очень приятно!"], 2),
      pick("Извините, где метро?", ["Спасибо, хорошо.", "Метро там, справа.", "Очень приятно!", "Он студент."], 1),
      pick("Спасибо!", ["Пожалуйста!", "Спасибо!", "Привет!", "Как дела?"], 0),
      pick("Ты студент?", ["Да, ты студент.", "Да, он студент.", "Да, я студент.", "Да, мы студенты."], 2, "Ты? (sen?) — javobda Я (men)."),
      pick("Вы студенты?", ["Да, я студенты.", "Да, мы студенты.", "Да, вы студент.", "Нет, они студент."], 1),
    ],
  },
  {
    title: "Как его зовут?",
    skill: "Olmoshlar",
    kind: "choice",
    instructions:
      "«зовут» bilan olmosh o'zgaradi: я → меня, ты → тебя, он → его, она → её, мы → нас, вы → вас, они → их. To'g'ri shaklni tanlang.",
    questions: [
      pick("Я — Олег. … зовут Олег.", ZOVUT, 0),
      pick("Ты — Анна? Как … зовут?", ZOVUT, 1),
      pick("Он студент. … зовут Иван.", ZOVUT, 2),
      pick("Она секретарь. … зовут Лена.", ZOVUT, 3),
      pick("Мы студенты. … зовут Маша и Саша.", ZOVUT, 4),
      pick("Вы директор? Как … зовут?", ZOVUT, 5, "Rasmiy murojaat — Вы, вас."),
      pick("Они спортсмены. … зовут Таня и Рома.", ZOVUT, 6),
      pick("Это Мария. … зовут Мария.", ZOVUT, 3),
      pick("Это Иван и Антон. … зовут Иван и Антон.", ZOVUT, 6),
      pick("— Как … зовут? — Меня зовут Катя.", ZOVUT, 1),
    ],
  },
  {
    title: "Qisqa ism",
    skill: "Ismlar",
    kind: "type",
    instructions:
      "Ruslar do'stlarini qisqa ism bilan chaqiradi: Александр → Саша. To'liq ismning qisqa shaklini yozing.",
    questions: [
      ["Александр", "Саша", "Александр → Саша."],
      ["Владимир", "Володя"],
      ["Николай", "Коля"],
      ["Алексей", "Лёша"],
      ["Михаил", "Миша"],
      ["Сергей", "Серёжа"],
      ["Мария", "Маша"],
      ["Екатерина", "Катя"],
      ["Елена", "Лена"],
      ["Наталья", "Наташа"],
    ].map(([prompt, answer, explanation]) => ({ prompt, answer, explanation })),
  },
  {
    title: "Как дела?",
    skill: "Kayfiyat",
    kind: "picture",
    instructions: "— Как дела? Yuz ifodasiga qarab javob bering.",
    questions: (
      [
        ["😄", 0],
        ["🙂", 1],
        ["😐", 2],
        ["😕", 3],
        ["😞", 4],
        ["🙂", 1],
        ["😞", 4],
        ["😄", 0],
        ["😕", 3],
        ["😐", 2],
      ] as const
    ).map(([emoji, correct]) => pick(emoji, MOOD, correct)),
  },
  {
    title: "Urg'u qayerda?",
    skill: "Fonetika",
    kind: "stress",
    instructions: "So'zni eshiting va urg'uli bo'g'inni bosing. Urg'usiz «о» [a] bo'lib o'qiladi.",
    questions: (
      [
        ["хо|ро|шо", 2, "хорошо́ [харашо́]"],
        ["спа|си|бо", 1],
        ["по|жа|луй|ста", 1],
        ["при|ят|но", 1],
        ["здрав|ствуй|те", 0],
        ["те|ле|фон", 2],
        ["со|ба|ка", 1],
        ["мо|ло|ко", 2, "молоко́ [малако́]"],
        ["го|род", 0],
        ["Моск|ва", 1],
      ] as [string, number, string?][]
    ).map(([syllables, correct, explanation]) => ({
      prompt: "Urg'uli bo'g'inni toping",
      audio: syllables.replace(/\|/g, ""),
      options: syllables.split("|"),
      correct,
      explanation,
    })),
  },
  {
    title: "Raqamni yozing",
    skill: "Raqamlar",
    kind: "number",
    instructions: "Raqam ruscha o'qiladi. Eshitgan raqamingizni sonlar bilan yozing (masalan: 7).",
    questions: [
      ["три", "3"],
      ["семь", "7"],
      ["одиннадцать", "11", "один + надцать = одиннадцать"],
      ["двенадцать", "12"],
      ["тринадцать", "13"],
      ["четырнадцать", "14"],
      ["пятнадцать", "15"],
      ["семнадцать", "17"],
      ["девятнадцать", "19"],
      ["двадцать", "20"],
    ].map(([audio, answer, explanation]) => ({ prompt: "Raqamni yozing", audio, answer, explanation })),
  },
  {
    title: "Gap tuzing",
    skill: "Gap tuzish",
    kind: "order",
    instructions: "So'zlarni to'g'ri tartibda bosib, gap tuzing.",
    questions: [
      "Меня зовут Анна.",
      "Как тебя зовут?",
      "Как Вас зовут?",
      "Это мама и папа.",
      "Он тоже студент.",
      "Мы тоже студенты.",
      "Извините, где метро?",
      "Метро там, справа.",
      "Её зовут Мария.",
      "Спасибо, очень хорошо.",
    ].map((answer) => ({ prompt: "Gap tuzing", answer })),
  },
  {
    title: "Bo'sh joyni to'ldiring",
    skill: "Yozish",
    kind: "fill",
    instructions: "Gapda bitta so'z tushib qolgan. Uni pastdagi klaviaturada ruscha yozing.",
    questions: [
      ["Меня ___ Олег.", "зовут"],
      ["Очень ___!", "приятно"],
      ["— Как ___? — Спасибо, хорошо.", "дела"],
      ["До ___!", "свидания"],
      ["Доброе ___!", "утро"],
      ["Извините, ___ метро?", "где"],
      ["— Спасибо! — ___!", "пожалуйста"],
      ["— Кто ___? — Это Анна.", "это"],
      ["Я студент. Он ___ студент.", "тоже"],
      ["Метро там, ___.", "справа|слева", "Ikkalasi ham to'g'ri: справа yoki слева."],
    ].map(([prompt, answer, explanation]) => ({ prompt, answer, explanation })),
  },
  {
    title: "Ayting",
    skill: "Talaffuz",
    kind: "speak",
    instructions: "Iborani eshiting, keyin mikrofon tugmasini bosib o'zingiz ayting.",
    questions: [
      "Здравствуйте!",
      "Очень приятно!",
      "Как дела?",
      "Спасибо, хорошо.",
      "До свидания!",
      "Извините, где метро?",
      "Меня зовут Анна.",
      "Кто это?",
      "Пожалуйста!",
      "Доброе утро!",
    ].map((phrase) => ({ prompt: phrase, answer: phrase })),
  },
];
