/**
 * 5-dars — «Живу, учусь, работаю» (Liden & Denz, «Я ❤ Русский Язык»,
 * 4-urok asosida): predlojniy kelishik (где? в/на), жить/учиться, kasb va
 * ish joyi, ofis buyumlari, manzil, baho ravishlari, потому что/поэтому,
 * женат/замужем. Lug'at 5 bosqich (50 so'z), 16 ta mashq. Gap, matn va
 * mashqlar o'zimizniki.
 */
import { scramble, type SeedExercise, type SeedQuestion } from "../seed-exercises";
import type { VocabSeed } from "./types";

const w = (
  emoji: string,
  word: string,
  transcription: string,
  pos: string,
  uz: string,
  def: string,
  ex: string,
  exUz: string
): VocabSeed => ({ emoji, word, transcription, pos, uz, def, ex, exUz });

export const R04_ROUNDS: { title: string; words: VocabSeed[] }[] = [
  {
    title: "1-bosqich",
    words: [
      w("🏦", "Банк", "bank", "ot", "Bank", "Там хранят деньги.", "Банк открыт до шести.", "Bank oltigacha ochiq."),
      w("🗃️", "Библиотека", "bibliatyéka", "ot", "Kutubxona", "Там берут и читают книги.", "Библиотека — тихое место для учёбы.", "Kutubxona — o'qish uchun tinch joy."),
      w("🏥", "Больница", "bal'nítsa", "ot", "Kasalxona", "Там работают врачи и лечат людей.", "Больница работает круглосуточно.", "Kasalxona kecha-kunduz ishlaydi."),
      w("🏨", "Гостиница", "gastínitsa", "ot", "Mehmonxona", "Там живут туристы.", "Гостиница с видом на море — мечта!", "Dengiz manzarali mehmonxona — orzu!"),
      w("🖥️", "Офис", "ófis", "ot", "Ofis", "Место, где работают менеджеры и секретари.", "Офис находится на десятом этаже.", "Ofis o'ninchi qavatda joylashgan."),
      w("🎟️", "Театр", "tiátr", "ot", "Teatr", "Там смотрят спектакли.", "Большой театр — символ Москвы.", "Katta teatr — Moskva ramzi."),
      w("🎓", "Университет", "univirsityét", "ot", "Universitet", "Там учатся студенты.", "Университет — это новые друзья и знания.", "Universitet — bu yangi do'stlar va bilimlar."),
      w("🧪", "Институт", "institút", "ot", "Institut", "Высшая школа, где учатся студенты.", "Институт находится в центре города.", "Institut shahar markazida joylashgan."),
      w("🛣️", "Улица", "úlitsa", "ot", "Ko'cha", "Дорога в городе, где стоят дома. Где? — на улице.", "Улица Навои — длинная и шумная.", "Navoiy ko'chasi — uzun va shovqinli."),
      w("🏘️", "Квартира", "kvartíra", "ot", "Kvartira", "Жильё в большом доме.", "Квартира маленькая, но очень уютная.", "Kvartira kichik, lekin juda shinam."),
    ],
  },
  {
    title: "2-bosqich",
    words: [
      w("🧑‍🏫", "Учитель", "uchítil'", "ot", "O'qituvchi (maktabda)", "Человек, который учит детей в школе.", "Хороший учитель — на всю жизнь.", "Yaxshi o'qituvchi — butun umrga."),
      w("🛒", "Продавец", "pradavyéts", "ot", "Sotuvchi", "Человек, который работает в магазине.", "Продавец дал мне скидку!", "Sotuvchi menga chegirma berdi!"),
      w("📊", "Экономист", "ekanamíst", "ot", "Iqtisodchi", "Человек, который работает с деньгами и цифрами.", "Экономист считает деньги компании.", "Iqtisodchi kompaniya pulini hisoblaydi."),
      w("🏅", "Тренер", "tryénir", "ot", "Murabbiy", "Человек, который учит спорту.", "Тренер кричит: «Ещё десять раз!»", "Murabbiy baqiradi: «Yana o'n marta!»"),
      w("🍸", "Бармен", "bármen", "ot", "Barmen", "Человек, который работает в баре.", "Бармен делает отличный кофе.", "Barmen a'lo qahva tayyorlaydi."),
      w("🗺️", "Гид", "git", "ot", "Gid", "Человек, который показывает город туристам.", "Гид показывает туристам Регистан.", "Gid sayyohlarga Registonni ko'rsatyapti."),
      w("🏺", "Экскурсовод", "ekskursavót", "ot", "Ekskursovod", "Человек, который рассказывает туристам о музее.", "Экскурсовод знает историю каждой картины.", "Ekskursovod har bir rasmning tarixini biladi."),
      w("🩰", "Балерина", "balirína", "ot", "Balerina", "Женщина, которая танцует балет.", "Балерина танцует как лебедь.", "Balerina oqqushdek raqsga tushadi."),
      w("🏡", "Жить", "zhit'", "fe'l", "Yashamoq", "Я живу, ты живёшь, он живёт, мы живём, вы живёте, они живут.", "Жить в большом городе интересно, но шумно.", "Katta shaharda yashash qiziq, lekin shovqinli."),
      w("🖊️", "Учиться", "uchít'sa", "fe'l", "O'qimoq (ta'lim olmoq)", "Я учусь, ты учишься, он учится, мы учимся, вы учитесь, они учатся.", "Учиться никогда не поздно!", "O'qishning erta-kechi yo'q!"),
    ],
  },
  {
    title: "3-bosqich",
    words: [
      w("🔑", "Ключ", "klyuch", "ot", "Kalit", "Им открывают дверь.", "Ключ от квартиры под ковриком.", "Kvartira kaliti gilamcha tagida."),
      w("📇", "Визитка", "vizítka", "ot", "Vizitka", "Маленькая карточка с именем и телефоном.", "Визитка — это ваше лицо.", "Vizitka — bu sizning yuzingiz."),
      w("🗒️", "Блокнот", "blaknót", "ot", "Bloknot", "Маленькая тетрадь для записей.", "Блокнот и ручка всегда в сумке.", "Bloknot va ruchka doim sumkada."),
      w("📅", "Календарь", "kalindár'", "ot", "Taqvim", "На нём дни, недели и месяцы.", "Календарь на стене показывает пятницу.", "Devordagi taqvim jumani ko'rsatyapti."),
      w("📁", "Папка", "pápka", "ot", "Papka", "В ней лежат документы.", "Папка с документами — на столе директора.", "Hujjatlar papkasi — direktorning stolida."),
      w("🌂", "Зонтик", "zóntik", "ot", "Soyabon (kichik)", "Маленький зонт.", "Зонтик забыл дома — и пошёл дождь!", "Soyabonni uyda unutdim — va yomg'ir yog'di!"),
      w("👛", "Кошелёк", "kashilyók", "ot", "Hamyon", "В нём носят деньги.", "Кошелёк пустой, а до зарплаты неделя!", "Hamyon bo'sh, maoshgacha esa bir hafta!"),
      w("🧥", "Пальто", "pal'tó", "ot", "Palto", "Тёплая одежда. Не изменяется: моё пальто.", "Пальто тёплое — зима не страшна!", "Palto issiq — qish qo'rqinchli emas!"),
      w("🛋️", "Диван", "diván", "ot", "Divan", "Большое мягкое место, где сидят.", "Диван — лучшее место в воскресенье.", "Divan — yakshanbada eng yaxshi joy."),
      w("🧱", "Стена", "stiná", "ot", "Devor", "Часть комнаты. Где? — на стене.", "Стена в моей комнате синяя.", "Xonamdagi devor ko'k."),
    ],
  },
  {
    title: "4-bosqich",
    words: [
      w("🌟", "Прекрасно", "prikrásna", "ravish", "Ajoyib", "Очень хорошо.", "Прекрасно! Ты сдал экзамен!", "Ajoyib! Imtihonni topshirding!"),
      w("😱", "Ужасно", "uzhásna", "ravish", "Dahshatli", "Очень плохо.", "Ужасно! Я опоздал на самолёт!", "Dahshat! Samolyotga kechikdim!"),
      w("💰", "Дорого", "dóraga", "ravish", "Qimmat", "Стоит много денег.", "В Париже всё очень дорого.", "Parijda hamma narsa juda qimmat."),
      w("🪙", "Дёшево", "dyósheva", "ravish", "Arzon", "Стоит мало денег.", "Фрукты на рынке стоят дёшево.", "Bozorda mevalar arzon turadi."),
      w("🧗", "Трудно", "trúdna", "ravish", "Qiyin", "Не легко.", "Трудно встать в шесть утра.", "Ertalab soat oltida turish qiyin."),
      w("🪶", "Легко", "likhkó", "ravish", "Oson", "Не трудно.", "Легко сказать, трудно сделать.", "Aytish oson, qilish qiyin."),
      w("🎉", "Весело", "vyésila", "ravish", "Quvnoq", "Радостно, не скучно.", "С друзьями всегда весело!", "Do'stlar bilan doim quvnoq!"),
      w("😢", "Грустно", "grúsna", "ravish", "G'amgin", "Не весело.", "Грустно, когда кончается отпуск.", "Ta'til tugaganda g'amgin bo'ladi."),
      w("🤩", "Интересно", "intiryésna", "ravish", "Qiziqarli", "Не скучно.", "Интересно, что будет завтра?", "Ertaga nima bo'lar ekan, qiziq?"),
      w("🥱", "Скучно", "skúshna", "ravish", "Zerikarli", "Не интересно.", "Без интернета скучно!", "Internetsiz zerikarli!"),
    ],
  },
  {
    title: "5-bosqich",
    words: [
      w("🤘", "Здорово", "zdórava", "ravish", "Zo'r", "Очень хорошо, отлично.", "Здорово, что ты пришёл!", "Kelganing zo'r bo'ldi!"),
      w("🫂", "Вместе", "vmyéste", "ravish", "Birga", "Не один, а с кем-то.", "Вместе мы — сила!", "Birga biz — kuchmiz!"),
      w("🛤️", "Далеко", "dalikó", "ravish", "Uzoqda", "Не близко.", "Луна очень далеко от Земли.", "Oy Yerdan juda uzoqda."),
      w("🔄", "Иногда", "inagdá", "ravish", "Ba'zan", "Не всегда, но бывает.", "Иногда я пою в душе.", "Ba'zan dushda qo'shiq aytaman."),
      w("👌", "Конечно", "kanyéshna", "ravish", "Albatta", "Да, точно.", "— Поможешь? — Конечно!", "— Yordam berasanmi? — Albatta!"),
      w("💍", "Женат", "zhinát", "sifat", "Uylangan (erkak)", "О мужчине, у которого есть жена.", "Мой брат уже женат.", "Akam allaqachon uylangan."),
      w("💒", "Замужем", "zámuzhim", "ravish", "Turmushga chiqqan (ayol)", "О женщине, у которой есть муж.", "Моя сестра замужем, у неё двое детей.", "Opam turmushga chiqqan, ikki farzandi bor."),
      w("➡️", "Поэтому", "paétamu", "bog'lovchi", "Shuning uchun", "Показывает результат.", "Я устал, поэтому иду спать.", "Charchadim, shuning uchun uxlashga ketyapman."),
      w("📮", "Адрес", "ádris", "ot", "Manzil", "Город, улица, дом, квартира.", "Напишите, пожалуйста, ваш адрес.", "Iltimos, manzilingizni yozing."),
      w("❔", "Где", "gdye", "so'roq", "Qayerda?", "Вопрос о месте.", "Где мой телефон?!", "Telefonim qayerda?!"),
    ],
  },
];

const pick = (prompt: string, options: string[], correct: number, explanation?: string): SeedQuestion => ({
  prompt,
  options,
  correct,
  explanation,
});
const listen = (audio: string, options: string[], explanation?: string): SeedQuestion => ({
  prompt: "Eshitgan gapingizni toping",
  audio,
  options,
  correct: options.indexOf(audio),
  explanation,
});

const V_NA = ["в", "на"];
const ZHENAT = ["женат", "замужем"];
const POTOMU = ["потому что", "поэтому"];
const ADV = ["дорого", "дёшево", "трудно", "легко", "весело", "грустно", "интересно", "скучно"];
const TF = ["To'g'ri", "Noto'g'ri"];
const TEXT =
  "Меня зовут Ольга. Мне 40 лет. Я учитель, работаю в школе. Я живу в Самаре, на улице Победы. Я замужем. Мой муж — экономист, он работает в банке. Наш сын учится в университете в Москве. Он говорит, что жить в Москве дорого, но интересно.";
const tf = (statement: string, isTrue: boolean, explanation?: string): SeedQuestion => ({
  prompt: `${TEXT}||${statement}`,
  options: TF,
  correct: isTrue ? 0 : 1,
  explanation,
});

export const R04_EXERCISES: SeedExercise[] = [
  {
    title: "Tinglang va toping",
    skill: "Tinglash",
    kind: "listen",
    instructions: "Gap ovoz chiqarib o'qiladi. Eshitgan gapingizni toping.",
    questions: [
      listen("Я в офисе.", ["Я в офисе.", "Я в кафе.", "Я дома.", "Я в банке."]),
      listen("Он живёт в Москве.", ["Он живёт в Москве.", "Он живёт в России.", "Она живёт в Москве.", "Он работает в Москве."]),
      listen("Мы учимся в университете.", ["Мы учимся в школе.", "Мы учимся в университете.", "Мы работаем в университете.", "Вы учитесь в университете."]),
      listen("Ключи на столе.", ["Ключи на столе.", "Ключи в сумке.", "Очки на столе.", "Ключи на стене."]),
      listen("Она работает в больнице.", ["Она работает в библиотеке.", "Она работает в больнице.", "Она работает в банке.", "Она учится в больнице."]),
      listen("Жить в Москве дорого.", ["Жить в Москве дорого.", "Жить в Москве дёшево.", "Жить в деревне дорого.", "Жить в Москве весело."]),
      listen("Где ты живёшь?", ["Где ты живёшь?", "Где ты работаешь?", "Где ты учишься?", "Где вы живёте?"]),
      listen("Я живу один.", ["Я живу один.", "Я живу одна.", "Мы живём вместе.", "Я живу там."], "один — erkak, одна — ayol."),
      listen("Учиться трудно, но интересно.", ["Учиться легко и интересно.", "Учиться трудно, но интересно.", "Работать трудно, но интересно.", "Учиться трудно и скучно."]),
      listen("Он женат.", ["Он женат.", "Она замужем.", "Он не женат.", "Они женаты."]),
    ],
  },
  {
    title: "В или на?",
    skill: "Grammatika",
    kind: "choice",
    instructions:
      "«в» — ichida (в сумке, в банке), «на» — ustida yoki ochiq joyda (на столе, на стене, на море, на улице).",
    questions: [
      pick("Телефон … столе.", V_NA, 1),
      pick("Очки … сумке.", V_NA, 0),
      pick("Календарь … стене.", V_NA, 1),
      pick("Цветы … вазе.", V_NA, 0),
      pick("Пальто … вешалке.", V_NA, 1),
      pick("Он работает … банке.", V_NA, 0),
      pick("Я живу … улице Пушкина.", V_NA, 1, "Ko'cha — на улице."),
      pick("Мы отдыхаем … море.", V_NA, 1, "Dengiz — на море."),
      pick("Она учится … университете.", V_NA, 0),
      pick("Документы … папке.", V_NA, 0),
    ],
  },
  {
    title: "Где? Qayerda?",
    skill: "Kelishik",
    kind: "choice",
    instructions:
      "«Где?» savolida so'z o'zgaradi: магазин → в магазине, музей → в музее, библиотека → в библиотеке, Россия → в России. «кафе, метро» o'zgarmaydi.",
    questions: [
      pick("Я в … (магазин)", ["магазин", "магазине", "магазина", "магазину"], 1),
      pick("Мы в … (библиотека)", ["библиотека", "библиотеку", "библиотеке", "библиотеки"], 2),
      pick("Они в … (музей)", ["музей", "музее", "музея", "музеи"], 1, "-й → -е: музей → в музее."),
      pick("Я живу в … (Россия)", ["Россие", "России", "Россию", "Россия"], 1, "-ия → -ии: Россия → в России."),
      pick("Он живёт в … (Москва)", ["Москва", "Москву", "Москве", "Москвы"], 2),
      pick("Она живёт во … (Франция)", ["Франции", "Франция", "Францие", "Францию"], 0),
      pick("Я учусь в … (университет)", ["университет", "университета", "университете", "университету"], 2),
      pick("Мы в … (гостиница)", ["гостиница", "гостинице", "гостиницу", "гостиницы"], 1),
      pick("Я в … (кафе)", ["кафе", "кафи", "кафа", "кафу"], 0, "Кафе, метро, радио o'zgarmaydi."),
      pick("Он на … (улица)", ["улица", "улице", "улицу", "улицы"], 1),
    ],
  },
  {
    title: "Kim qayerda ishlaydi?",
    skill: "Juftlik",
    kind: "match",
    instructions: "Kasbni ish joyi bilan yoki ruscha so'zni tarjimasi bilan ulang.",
    questions: [
      ["преподаватель|университет", "актёр|театр", "врач|больница", "продавец|магазин"],
      ["экономист|банк", "учитель|школа", "официант|ресторан", "тренер|фитнес-клуб"],
      ["бармен|бар", "экскурсовод|музей", "студент|университет", "школьник|школа"],
      ["банк|bank", "больница|kasalxona", "библиотека|kutubxona", "гостиница|mehmonxona"],
      ["театр|teatr", "улица|ko'cha", "квартира|kvartira", "офис|ofis"],
      ["учитель|o'qituvchi", "продавец|sotuvchi", "тренер|murabbiy", "экскурсовод|ekskursovod"],
      ["ключ|kalit", "кошелёк|hamyon", "зонтик|soyabon", "пальто|palto"],
      ["визитка|vizitka", "блокнот|bloknot", "календарь|taqvim", "папка|papka"],
      ["женат|uylangan (erkak)", "замужем|turmushga chiqqan (ayol)", "вместе|birga", "далеко|uzoqda"],
      ["один|yolg'iz (erkak)", "одна|yolg'iz (ayol)", "иногда|ba'zan", "конечно|albatta"],
    ].map((options) => ({ prompt: "Juftlarni ulang", options })),
  },
  {
    title: "Жить va учиться",
    skill: "Fe'llar",
    kind: "fill",
    instructions:
      "жить: я живу, ты живёшь, он живёт, мы живём, вы живёте, они живут. учиться: я учусь, ты учишься, он учится, мы учимся, вы учитесь, они учатся.",
    questions: [
      ["Я ___ в Москве. (жить)", "живу"],
      ["Ты ___ в Германии? (жить)", "живёшь"],
      ["Он ___ во Франции. (жить)", "живёт"],
      ["Мы ___ в Англии. (жить)", "живём"],
      ["Вы ___ в Америке? (жить)", "живёте"],
      ["Они ___ в Испании. (жить)", "живут"],
      ["Я ___ в университете. (учиться)", "учусь"],
      ["Ты ещё ___ в школе? (учиться)", "учишься"],
      ["Он ___ в институте. (учиться)", "учится"],
      ["Где они ___? (учиться)", "учатся"],
    ].map(([prompt, answer]) => ({ prompt, answer })),
  },
  {
    title: "Qarama-qarshisini toping",
    skill: "Antonimlar",
    kind: "match",
    instructions: "So'zni qarama-qarshi ma'nodagi so'z yoki tarjimasi bilan ulang.",
    questions: [
      ["хорошо|плохо", "легко|трудно", "интересно|скучно", "весело|грустно"],
      ["дёшево|дорого", "прекрасно|ужасно", "много|мало", "далеко|близко"],
      ["уже|ещё", "всегда|никогда", "тут|там", "слева|справа"],
      ["дорого|qimmat", "дёшево|arzon", "трудно|qiyin", "легко|oson"],
      ["весело|quvnoq", "грустно|g'amgin", "интересно|qiziq", "скучно|zerikarli"],
      ["прекрасно|ajoyib", "ужасно|dahshatli", "здорово|zo'r", "иногда|ba'zan"],
      ["хорошо|yaxshi", "плохо|yomon", "вместе|birga", "один|yolg'iz"],
      ["легко|трудно", "дорого|дёшево", "скучно|интересно", "грустно|весело"],
      ["ужасно|прекрасно", "мало|много", "плохо|хорошо", "там|тут"],
      ["конечно|albatta", "далеко|uzoq", "вместе|birga", "поэтому|shuning uchun"],
    ].map((options) => ({ prompt: "Juftlarni ulang", options })),
  },
  {
    title: "Bu nima?",
    skill: "Rasm",
    kind: "picture",
    instructions: "Rasmga qarang va uning ruscha nomini toping.",
    questions: [
      pick("🔑", ["ключ", "кошелёк", "зонтик", "папка"], 0),
      pick("📇", ["календарь", "визитка", "блокнот", "пальто"], 1),
      pick("🗒️", ["папка", "блокнот", "ключ", "диван"], 1),
      pick("📅", ["стена", "визитка", "календарь", "пиджак"], 2),
      pick("📁", ["папка", "полка", "ваза", "ключ"], 0),
      pick("🌂", ["пальто", "зонтик", "кошелёк", "вешалка"], 1, "Зонтик — kichik soyabon (зонт)."),
      pick("👛", ["кошелёк", "ключ", "блокнот", "папка"], 0),
      pick("🧥", ["пиджак", "диван", "пальто", "зонтик"], 2),
      pick("🏦", ["банк", "больница", "библиотека", "театр"], 0),
      pick("🏥", ["гостиница", "больница", "офис", "школа"], 1),
    ],
  },
  {
    title: "Qanday?",
    skill: "Vaziyat",
    kind: "situation",
    instructions: "O'zbekcha gapni o'qing va mos ruscha so'zni tanlang.",
    questions: [
      pick("Moskvada yashash qimmat. — Жить в Москве …", ADV.slice(0, 4), 0),
      pick("Qishloqda yashash arzon. — Жить в деревне …", ADV.slice(0, 4), 1),
      pick("Universitetda o'qish qiyin. — Учиться в университете …", ADV.slice(0, 4), 2),
      pick("Maktabda o'qish oson. — Учиться в школе …", ADV.slice(0, 4), 3),
      pick("Ota-onam bilan yashash quvnoq. — Жить с родителями …", ADV.slice(4), 0),
      pick("Yolg'iz yashash g'amgin. — Жить одному …", ADV.slice(4), 1),
      pick("Rus tilini o'rganish qiziq. — Изучать русский язык …", ADV.slice(4), 2),
      pick("Kechqurun ishlash zerikarli. — Работать вечером …", ADV.slice(4), 3),
      pick("Bu ajoyib! — Это …!", ["прекрасно", "ужасно", "дёшево", "скучно"], 0),
      pick("Bu dahshatli! — Это …!", ["здорово", "ужасно", "легко", "интересно"], 1),
    ],
  },
  {
    title: "Suhbatni davom ettiring",
    skill: "Dialog",
    kind: "dialog",
    instructions: "Suhbatdoshingiz savol berdi. Mos javobni tanlang.",
    questions: [
      pick("Где ты живёшь?", ["Я живу в Москве.", "Я живу Москва.", "Я в Москву.", "Москва живу."], 0),
      pick("Где работает твой брат?", ["Он работает в банке.", "Он работает банк.", "Он в банк.", "Он банке."], 0),
      pick("Где мои ключи?", ["Они на столе.", "Он на столе.", "Они на стол.", "Они стол."], 0),
      pick("Ты работаешь или учишься?", ["Я учусь в университете.", "Я учишься в университете.", "Я учусь университет.", "Да, работаю."], 0),
      pick("Где ты сейчас?", ["Я в кафе.", "Я кафе.", "Я на кафе.", "В кафу."], 0),
      pick("Жить в Москве дорого?", ["Да, очень дорого.", "Да, очень дорогой.", "Да, в Москве.", "Нет, я не живу."], 0),
      pick("Ваш адрес?", ["Улица Пушкина, дом 5.", "Я живу хорошо.", "Меня зовут Пушкин.", "Мне 5 лет."], 0),
      pick("Вы женаты?", ["Да, женат.", "Да, замужем.", "Да, женатый.", "Да, жена."], 0, "Erkak — «женат», ayol — «замужем»."),
      pick("Почему ты не работаешь?", ["Потому что я учусь.", "Поэтому я учусь.", "Почему я учусь.", "Я учусь поэтому."], 0),
      pick("Где работает учитель?", ["В школе.", "В школа.", "На школе.", "Школу."], 0),
    ],
  },
  {
    title: "To'g'ri yoki noto'g'ri?",
    skill: "O'qish",
    kind: "truefalse",
    instructions: "Matnni o'qing va gap to'g'ri yoki noto'g'ri ekanini belgilang.",
    questions: [
      tf("Ольга — учитель.", true),
      tf("Ольга работает в банке.", false, "Ольга работает в школе, а в банке работает её муж."),
      tf("Ольга живёт в Москве.", false, "Она живёт в Самаре."),
      tf("Ольга замужем.", true),
      tf("Её муж — экономист.", true),
      tf("Сын Ольги работает в Москве.", false, "Сын учится в университете в Москве."),
      tf("Семья живёт на улице Победы.", true),
      tf("Ольге 40 лет.", true),
      tf("Сын думает, что жить в Москве дёшево.", false, "Он думает, что жить в Москве дорого."),
      tf("Сын думает, что жить в Москве интересно.", true),
    ],
  },
  {
    title: "Потому что или поэтому?",
    skill: "Bog'lovchi",
    kind: "choice",
    instructions: "«потому что» — chunki (sababni aytadi), «поэтому» — shuning uchun (natijani aytadi).",
    questions: [
      pick("Он плохо говорит по-русски, … мало изучает язык.", POTOMU, 0),
      pick("Он мало изучает язык, … плохо говорит по-русски.", POTOMU, 1),
      pick("Я живу один, … мне грустно.", POTOMU, 1),
      pick("Мне грустно, … я живу один.", POTOMU, 0),
      pick("Жить в Москве дорого, … мы живём в деревне.", POTOMU, 1),
      pick("Мы живём в деревне, … жить в Москве дорого.", POTOMU, 0),
      pick("Я не работаю, … я учусь.", POTOMU, 0),
      pick("Я учусь, … я не работаю.", POTOMU, 1),
      pick("Родители много работают, … мы мало отдыхаем вместе.", POTOMU, 1),
      pick("Мы мало отдыхаем вместе, … родители много работают.", POTOMU, 0),
    ],
  },
  {
    title: "Женат или замужем?",
    skill: "Oila holati",
    kind: "choice",
    instructions: "Erkak haqida — «женат» (uylangan), ayol haqida — «замужем» (turmushga chiqqan).",
    questions: [
      pick("Иван …", ZHENAT, 0),
      pick("Анна …", ZHENAT, 1),
      pick("Мой брат …", ZHENAT, 0),
      pick("Моя сестра …", ZHENAT, 1),
      pick("Мой папа …", ZHENAT, 0),
      pick("Моя подруга …", ZHENAT, 1),
      pick("Этот мужчина …", ZHENAT, 0),
      pick("Эта женщина …", ZHENAT, 1),
      pick("Мой друг Олег уже …", ZHENAT, 0),
      pick("Катя ещё не …", ZHENAT, 1),
    ],
  },
  {
    title: "Harflardan so'z",
    skill: "Harflar",
    kind: "anagram",
    instructions: "Harflar aralashib ketgan. Ularni to'g'ri tartibda bosib, so'zni yig'ing.",
    questions: ["библиотека", "больница", "гостиница", "университет", "квартира", "календарь", "кошелёк", "экономист", "учитель", "интересно"].map(
      (word) => ({ prompt: scramble(word), answer: word })
    ),
  },
  {
    title: "Manzilni yozing",
    skill: "Raqamlar",
    kind: "number",
    instructions: "Manzil ruscha o'qiladi. Uy yoki kvartira raqamini sonlar bilan yozing.",
    questions: [
      ["Дом девяносто четыре.", "94"],
      ["Квартира сто четырнадцать.", "114", "сто + четырнадцать = 114."],
      ["Дом пятнадцать.", "15"],
      ["Квартира сорок пять.", "45"],
      ["Дом тридцать пять.", "35"],
      ["Квартира девятнадцать.", "19"],
      ["Дом семь.", "7"],
      ["Дом пятьдесят два.", "52"],
      ["Квартира восемьдесят.", "80"],
      ["Дом двенадцать.", "12"],
    ].map(([audio, answer, explanation]) => ({ prompt: "Raqamni yozing", audio, answer, explanation })),
  },
  {
    title: "Gap tuzing",
    skill: "Gap tuzish",
    kind: "order",
    instructions: "So'zlarni to'g'ri tartibda bosib, gap tuzing.",
    questions: [
      "Я живу в Москве.",
      "Где ты работаешь?",
      "Он учится в университете.",
      "Ключи на столе.",
      "Мы живём на улице Ленина.",
      "Жить в деревне скучно.",
      "Мой брат работает в банке.",
      "Мы всё делаем вместе.",
      "Она живёт в квартире 19.",
      "Учиться трудно, но интересно.",
    ].map((answer) => ({ prompt: "Gap tuzing", answer })),
  },
  {
    title: "Ayting",
    skill: "Talaffuz",
    kind: "speak",
    instructions: "Gapni eshiting, keyin mikrofon tugmasini bosib o'zingiz ayting.",
    questions: [
      "Я живу в Москве.",
      "Я учусь в университете.",
      "Он работает в банке.",
      "Где ты живёшь?",
      "Жить в Москве дорого.",
      "Ключи на столе.",
      "Я работаю в офисе.",
      "Учиться интересно, но трудно.",
      "Мы живём вместе.",
      "Я замужем.",
    ].map((phrase) => ({ prompt: phrase, answer: phrase })),
  },
];
